spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/plants
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.jpa.hibernate.ddl-auto=update
